package tim;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdk.javadoc.internal.tool.Main;

/**
 *
 * @author LENOVO
 */
public class ventanaprincipal extends javax.swing.JFrame {

    int miliseg = 0;
    int seg = 0;
    int min = 0;
    int hor = 0;
    boolean estado = true;

    /**
     * Creates new form ventanaprincipal
     */
    public ventanaprincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cerrar();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/ControlInventario.png")).getImage());
        tiempo();
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"));
        Image image = icon.getImage();
        Escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jToolBar1 = new javax.swing.JToolBar();
        txtcrono = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemProgramadores = new javax.swing.JMenuItem();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuRegistros = new javax.swing.JMenu();
        menuItemEmpleados = new javax.swing.JMenuItem();
        menuItemHorario_Trabajo = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuDocumental = new javax.swing.JMenu();
        menuItemYoutube = new javax.swing.JMenuItem();
        jMenuItemPdfDocumental = new javax.swing.JMenuItem();
        menuComunicacionAsesor = new javax.swing.JMenu();
        menuItemCorreo = new javax.swing.JMenuItem();
        menuItemWhatsApp = new javax.swing.JMenuItem();
        MenuItemTelegram = new javax.swing.JMenuItem();
        menuItemFacebook = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de Inventario");

        jToolBar1.setRollover(true);

        txtcrono.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtcrono.setForeground(new java.awt.Color(255, 0, 51));
        txtcrono.setText("00 : 00 : 00");
        jToolBar1.add(txtcrono);

        Escritorio.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addGap(0, 533, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );

        BarraMenu.setAutoscrolls(true);

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Archivo.png"))); // NOI18N
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        menuItemProgramadores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemProgramadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Grupo.png"))); // NOI18N
        menuItemProgramadores.setText("Programador");
        menuItemProgramadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProgramadoresActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemProgramadores);

        menuItemCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar.png"))); // NOI18N
        menuItemCerrarSesion.setText("Cerrar sesión");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemCerrarSesion);

        BarraMenu.add(menuArchivo);

        menuRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registros.png"))); // NOI18N
        menuRegistros.setText("Registros");
        menuRegistros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        menuItemEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientess.jpg"))); // NOI18N
        menuItemEmpleados.setText("Empleados");
        menuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpleadosActionPerformed(evt);
            }
        });
        menuRegistros.add(menuItemEmpleados);

        menuItemHorario_Trabajo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemHorario_Trabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horario_trabajo.jpg"))); // NOI18N
        menuItemHorario_Trabajo.setText("Horario de Trabajo");
        menuItemHorario_Trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHorario_TrabajoActionPerformed(evt);
            }
        });
        menuRegistros.add(menuItemHorario_Trabajo);

        BarraMenu.add(menuRegistros);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ayuda.png"))); // NOI18N
        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        menuDocumental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.jpg"))); // NOI18N
        menuDocumental.setText("Documental");
        menuDocumental.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuItemYoutube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Youtube.png"))); // NOI18N
        menuItemYoutube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemYoutubeActionPerformed(evt);
            }
        });
        menuDocumental.add(menuItemYoutube);

        jMenuItemPdfDocumental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Documental.png"))); // NOI18N
        jMenuItemPdfDocumental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPdfDocumentalActionPerformed(evt);
            }
        });
        menuDocumental.add(jMenuItemPdfDocumental);

        menuAyuda.add(menuDocumental);

        menuComunicacionAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llamenos.jpg"))); // NOI18N
        menuComunicacionAsesor.setText("Comuníquese con un asesor");
        menuComunicacionAsesor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        menuItemCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Correo.png"))); // NOI18N
        menuItemCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCorreoActionPerformed(evt);
            }
        });
        menuComunicacionAsesor.add(menuItemCorreo);

        menuItemWhatsApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp.png"))); // NOI18N
        menuItemWhatsApp.setText("948287337");
        menuItemWhatsApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemWhatsAppActionPerformed(evt);
            }
        });
        menuComunicacionAsesor.add(menuItemWhatsApp);

        MenuItemTelegram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Telegram.png"))); // NOI18N
        MenuItemTelegram.setText("948287337");
        MenuItemTelegram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemTelegramActionPerformed(evt);
            }
        });
        menuComunicacionAsesor.add(MenuItemTelegram);

        menuItemFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Facebook.png"))); // NOI18N
        menuItemFacebook.setText("Kenyi Tim");
        menuItemFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFacebookActionPerformed(evt);
            }
        });
        menuComunicacionAsesor.add(menuItemFacebook);

        menuAyuda.add(menuComunicacionAsesor);

        BarraMenu.add(menuAyuda);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemHorario_TrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHorario_TrabajoActionPerformed
        // TODO add your handling code here:
        horario_trabajo j = new horario_trabajo();
        Escritorio.add(j);
        j.show();
    }//GEN-LAST:event_menuItemHorario_TrabajoActionPerformed

    private void menuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpleadosActionPerformed
        // TODO add your handling code here:
        empleado em = new empleado();
        Escritorio.add(em);
        em.show();
    }//GEN-LAST:event_menuItemEmpleadosActionPerformed

    private void menuItemYoutubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemYoutubeActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=Hstep4SsSrE&list=RDHstep4SsSrE&start_radio=1").toURI());
        } catch (URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemYoutubeActionPerformed

    private void menuItemWhatsAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemWhatsAppActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("https://wa.me/51978308860?text=Hola%20necesito%20información").toURI());
        } catch (URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemWhatsAppActionPerformed

    private void menuItemFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFacebookActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("https://web.facebook.com/DiocesisDeHuanuco").toURI());
        } catch (URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemFacebookActionPerformed

    private void jMenuItemPdfDocumentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPdfDocumentalActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("https://drive.google.com/file/d/1mxdXkAsj0tcJvkddspPbpEk-Z5GIKbbi/view?usp=sharing").toURI());
        } catch (URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPdfDocumentalActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArchivoActionPerformed

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "¿Está seguro de salir?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            estado = false;
            JOptionPane.showMessageDialog(null, "Gracias por su visita");
            System.exit(0);
        }
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void MenuItemTelegramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemTelegramActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("https://t.me/fer3030inoHTasYu19t46gduev679").toURI());
        } catch (URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuItemTelegramActionPerformed

    private void menuItemCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCorreoActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("mailto:fernandonos3021@gmail.com?subject=Consultas&").toURI());
        } catch (URISyntaxException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemCorreoActionPerformed

    private void menuItemProgramadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProgramadoresActionPerformed
        // TODO add your handling code here:
        programadores pro = new programadores();
        Escritorio.add(pro);
        pro.show();
    }//GEN-LAST:event_menuItemProgramadoresActionPerformed

    ///=====================================
    public void cerrar() {
        try {
            this.setDefaultCloseOperation(ventanaprincipal.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "CIERRE SESIÓN PARRA SALIR", "Advertencia", JOptionPane.CLOSED_OPTION);

    }
    ///===========================================

    public void tiempo() {
        estado = true;
        Thread hilo = new Thread() {
            public void run() {
                for (;;) {
                    if (estado == true) {
                        try {
                            sleep(1);
                            if (miliseg >= 1000) {
                                miliseg = 0;
                                seg++;
                            }
                            if (seg >= 60) {
                                miliseg = 0;
                                seg = 0;
                                min++;
                            }
                            if (min >= 60) {
                                miliseg = 0;
                                seg = 0;
                                min = 0;
                                hor++;
                            }
                            txtcrono.setText(hor + " : " + min + " : " + seg);
                            miliseg++;
                        } catch (Exception e) {
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        hilo.start();
    }
    //====================================================================
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MenuItemTelegram;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem jMenuItemPdfDocumental;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuComunicacionAsesor;
    private javax.swing.JMenu menuDocumental;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemCorreo;
    private javax.swing.JMenuItem menuItemEmpleados;
    private javax.swing.JMenuItem menuItemFacebook;
    private javax.swing.JMenuItem menuItemHorario_Trabajo;
    private javax.swing.JMenuItem menuItemProgramadores;
    private javax.swing.JMenuItem menuItemWhatsApp;
    private javax.swing.JMenuItem menuItemYoutube;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JLabel txtcrono;
    // End of variables declaration//GEN-END:variables
}
